name: easymd
channels:
  - conda-forge
dependencies:
  - python=3.10
  - typer>=0.16.0
  - click>=8.0.0
  - pdbfixer=1.9
  - openff-toolkit=0.14.5
  - openmmforcefields=0.12.0
  - openmm=8.2.0         # from conda-forge (includes GPU plugins)
  - cuda-version=12      # match the user’s CUDA runtime
  - mdanalysis=2.8.0
  - numpy=1.26.4
  - rdkit=2023.03.3
  - biopython=1.85
  - tqdm
  - requests
  - pip
  - pip:
      - termol==0.1.6